<?php
/** @var \Magenest\Popup\Block\Adminhtml\Popup\FloatingButton\PreviewButton $block
 */
?>

<div class="floating-button-preview"  <?= isset($secureRenderer) ? '' : 'style= "'.$block->getDisplayButton().'"' ?>>
    <div class="title"><strong><?= $block->escapeHtml(__('Floating Button Preview')) ?></strong></div>
    <div class="magenest-popup-action"
    <span id="floating-button-content"></span>
</div>
</div>
<?= isset($secureRenderer) ? $secureRenderer->renderStyleAsTag($block->getDisplayButton(), '.floating-button-preview') : ''?>
